-- =======================
-- Main BriefingRoom table
-- =======================

briefingRoom = {} -- Main BriefingRoom table

briefingRoom.mission = {} -- Main BriefingRoom mission table
briefingRoom.mission.f10Menu = { } -- Mission F10Menu
briefingRoom.mission.f10Menu.objectives = { }
briefingRoom.mission.objectives = {} -- Main objective table
briefingRoom.mission.objectives.data = {}
briefingRoom.mission.objectives.trigger = {}
briefingRoom.mission.objectives.features = {}

-- =============================================
-- Objectives tables (generated by BriefingRoom)
-- =============================================
$SCRIPTOBJECTIVES$

-- ===============================================
-- Objectives triggers (generated by BriefingRoom)
-- ===============================================
$SCRIPTOBJECTIVESTRIGGERS$

-- ===============================================
-- Objectives features (generated by BriefingRoom)
-- ===============================================
$SCRIPTOBJECTIVESFEATURES$

-- ============================================
-- Mission features (generated by BriefingRoom)
-- ============================================
$SCRIPTMISSIONFEATURES$
