-- =======================
-- Main BriefingRoom table
-- =======================

briefingRoom = {} -- Main BriefingRoom table

briefingRoom.mission = {} -- Main BriefingRoom mission table
briefingRoom.mission.f10Menu = { } -- Mission F10Menu
briefingRoom.mission.f10Menu.objectives = { }
briefingRoom.mission.objectives = {} -- Main objective table
briefingRoom.mission.objectives.data = {}
briefingRoom.mission.objectives.trigger = {}
briefingRoom.mission.objectives.features = {}

-- =============================================
-- Objectives tables (generated by BriefingRoom)
-- =============================================
$OBJECTIVES_LUA$

-- ===============================================
-- Objectives triggers (generated by BriefingRoom)
-- ===============================================
$OBJECTIVES_TRIGGERS_LUA$

-- ===============================================
-- Objectives features (generated by BriefingRoom)
-- ===============================================
$OBJECTIVES_FEATURES_LUA$

-- ============================================
-- Mission features (generated by BriefingRoom)
-- ============================================
$MISSION_FEATURES_LUA$
