  ["mass"] = 1000,
  ["category"] = "Cargos",
  ["canCargo"] = true,
  ["rate"] = 100,
  ["shape_name"] = "$SHAPE$",
  ["type"] = "$DCSID$",
  ["unitId"] = $UNITID$,
$EXTRALUA$
  ["y"] = $UNITY$,
  ["x"] = $UNITX$,
  ["name"] = "$NAME$",
  ["heading"] = $HEADING$,
